{% set name = "pytest-selenium" %}
{% set version = "3.0.0" %}
{% set hash = "0589c4a9433e5ae8c35efbd97ba226e617cd61d756f52b17608ccf022fc60320" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - pip
    - poetry
    - python >=3.6.2

  run:
    - python >=3.6.2
    - pytest >=6.0.0
    - pytest-base-url >=1.4.2
    - pytest-html >=1.14.0
    - pytest-variables >=1.5.0
    - requests >=2.26.0
    - selenium 3.*
    - tenacity 6.*

test:
  imports:
    - pytest_selenium
    - pytest_selenium.drivers

about:
  home: https://pypi.python.org/pypi/pytest-selenium
  dev_url: https://github.com/pytest-dev/pytest-selenium
  license: MPL-2.0
  license_file: LICENSE
  summary: pytest-selenium is a plugin for py.test that provides support for running Selenium based tests.

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
