{% set name = "pytest-selenium" %}
{% set version = "1.15.1" %}
{% set hash_type = "sha256" %}
{% set hash = "798684c72b6dd3c70768903813e6055938a30049de28809882428feb5db9033e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  build:
    - pip
    - python
    - setuptools
    - setuptools_scm    

  run:
    - python
    - pytest >=3.0
    - pytest-base-url
    - pytest-html >=1.14.0
    - pytest-variables >=1.5.0
    - selenium >=3.0.0
    - requests

test:
  imports:
    - pytest_selenium
    - pytest_selenium.drivers

about:
  home: https://pypi.python.org/pypi/pytest-selenium
  license: MPL 2.0
  license_file: LICENSE
  summary: pytest-selenium is a plugin for py.test that provides support for running Selenium based tests.

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
