{% set name = "pytest-selenium" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b0a4e1f27750cde631c513c87ae4863dcf9e180e5a1d680a66077da8a669156c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatch-vcs >=0.3
    - hatchling >=1.13

  run:
    - python >={{ python_min }}
    - pytest >=6.0
    - pytest-base-url >=2.0.0
    - pytest-html >=4.0.0
    - pytest-variables >=2.0.0
    - requests >=2.26.0
    - selenium >=4.10.0
    - tenacity >=6.0.0

  run_constrained:
    - appium-python-client >=1.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_selenium
    - pytest_selenium.drivers

about:
  home: https://pypi.python.org/pypi/pytest-selenium
  dev_url: https://github.com/pytest-dev/pytest-selenium
  summary: pytest-selenium is a plugin for py.test that provides support for running Selenium based tests.
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
