{% set name = "pytest-selenium" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-selenium-{{ version }}.tar.gz
  sha256: a0b45a0d1d5833a67b14a279cfe1a0eeaf4981ab4b0d12e9787fcfa1ed48049f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1.0.0

  run:
    - python >=3.7
    - pytest-base-url >=2.0.0
    - pytest-html >=2.0.0
    - pytest-variables >=2.0.0
    - pytest >=6.0    
    - requests >=2.26.0
    - selenium >=4.0.0
    - tenacity >=6.0.0
  
  run_constrained:
    - appium-python-client >=1.0.0

test:
  imports:
    - pytest_selenium
    - pytest_selenium.drivers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.python.org/pypi/pytest-selenium
  summary: pytest-selenium is a plugin for py.test that provides support for running Selenium based tests.
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
